<h1 style='text-align: center'>Level Up: 挑战你的 numpy 技能</h1>

### 挑战 1 ：引入 numpy 并查看 numpy 的版本。
要求：这是第一步，以后我们使用 numpy 时都将用别名 np。

In [1]:
# 答案
import numpy as np
print(np.__version__)

1.14.0


### 挑战 2 ：创建数组
要求：创建一维数组，内容为从 0 到 9。

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 挑战 3 ：创建布尔数组
要求：数组大小为 3*3，全部为 True。

In [3]:
# 答案一：
a1 = np.full((3, 3), True, dtype=bool)
print(a1)

# 答案二：
a2 = np.ones((3,3), dtype=bool)
print(a2)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### 挑战 4 ：按要求抽取数组中的元素
要求：原数组 arr 为一维数组，内容为从 0 到 9，抽取出所有奇数。

```python
# 输入数组
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [4]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 == 1]
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 挑战 5 ：按要求修改数组中的元素（原地修改）
要求：原数组为一维数组，内容为从 0 到 9，将所有奇数原地修改为 -1。

```python
# 输入数组
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### 挑战 6 ：按要求修改数组中的元素（返回新数组）
要求：原数组为一维数组，内容为从 0 到 9，返回一个该数组的拷贝，其中奇数修改为 -1。

In [6]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### 挑战 7 ：修改数组的形状
要求：将给定的一维数组 arr 转为为二维数组，其中新数组的行数为2。

In [7]:
arr = np.arange(10)
arr.reshape(2, -1)  # -1 表示自动计算该维度的大小

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 挑战 8 ：合并数组（列方向）
要求：将给定数组在列方向上合并。

```python
# 输入数组
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [8]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# 答案 1:
np.concatenate([a, b], axis=0)

# 答案 2:
np.vstack([a, b])

# 答案 3:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### 挑战 9 ：合并数组（水平方向）
要求：将给定数组在水平方向上合并。

```python
# 输入数组
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [9]:
# 输入数组
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# 答案 1:
np.concatenate([a, b], axis=1)
# 答案 2:
np.hstack([a, b])

# 答案 3:
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### 挑战 10 ：创建数组（进阶）
要求：不用硬编码，使用内置方法，从给定数组 a 生成数组 b。
其中
```python
# 输入数组
a = np.array([1,2,3])
b = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [10]:
a = np.array([1,2,3])
b = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# 答案
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

### 挑战 11 ：返回公共元素
要求：给定两个数组 a、b，要求返回这两个数组元素的交集。

```python
# 输入数组
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [11]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

### 挑战 12 ：删除元素
要求：给定两个数组 a、b，从数组 a 中删除 b 中出现的元素。

```python
# 输入数组
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```

In [12]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

### 挑战 13 ：找出相同元素
要求：给定两个数组 a、b，返回两数组中相同元素的下标。

```python
# 输入数组
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [13]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

### 挑战 14 ：按要求取出元素
要求：从数组 a 中取出大于等于 5 且小于等于 10 的元素。

```python
# 输入数组
a = np.arange(15)
```

In [14]:
a = np.arange(15)

# 答案 1:
index = np.where((a >= 5) & (a <= 10))
a[index]

# 答案 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

# 答案 3:
a[(a >= 5) & (a <= 10)]

array([ 5,  6,  7,  8,  9, 10])

### 挑战 15 ：实现 max 的 numpy 版
要求：给定长度相同的数组 a、b，返回一个新数组，数组上的每一个元素为 max(a_i, b_i)。
若 pair_max 为满足要求的函数，则对于 a 和 b，期望输出如下

```python
# 输入数组
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#> 期望输出：array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])
```

In [15]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

# 答案:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

### 挑战 16 ：交换二维数组的列
要求：交换数组 arr 的第一第二列。

```python
# 输入数组
arr = np.arange(9).reshape(3,3)
```

In [16]:
arr = np.arange(9).reshape(3,3)

# 答案:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

### 挑战 17 ：交换二维数组的行
要求：交换二维数组 arr 的第一第二行。

```python
# 输入数组
arr = np.arange(9).reshape(3,3)
```

In [17]:
arr = np.arange(9).reshape(3,3)
# 答案
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

### 挑战 18 ：将一个数组按行反序
要求：数组 arr 为二维数组，将其行反序。
```python
# 输入数组
arr = np.arange(9).reshape(3,3)
```

In [18]:
arr = np.arange(9).reshape(3,3)

# 答案:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

### 挑战 19 ：将一个数组按列反序
要求：数组 arr 为二维数组，将其列反序。

```python
# 输入数组
arr = np.arange(9).reshape(3,3)
```

In [19]:
arr = np.arange(9).reshape(3,3)

# 答案:
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

### 挑战 20 ：创建随机数组
要求：创建一个 5*3 的数组，数组元素为 5 到 10 的随机浮点数。

In [20]:
# 答案 1:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))

# 答案 2:
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[ 8.51572023  9.43701914  5.33778609]
 [ 7.85916219  6.38096813  9.92712505]
 [ 5.51979229  7.85928664  7.49294511]
 [ 6.59099471  5.77526055  6.16361369]
 [ 6.44329631  5.40663434  9.05989878]]


### 挑战 21 ：按要求打印数组（一）
要求：rand_arr 数组元素输出时保留 3 位小数。
```python
# 输入数组
rand_arr = np.random.random([5,3])
```

In [21]:
rand_arr = np.random.random([5,3])

# 答案
np.set_printoptions(precision=3)
rand_arr[:4]

array([[ 0.988,  0.069,  0.263],
       [ 0.67 ,  0.38 ,  0.761],
       [ 0.077,  0.631,  0.05 ],
       [ 0.315,  0.87 ,  0.436]])

### 挑战 22 ：按要求打印数组（二）
要求：rand_arr 数组为小数，使用小数点的形式来打印，而不是科学记数法（如1e-4）。
```python
# 输入数组

np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

#> 期望输出： array([[  5.434049e-04,   2.783694e-04,   4.245176e-04],
#>                 [  8.447761e-04,   4.718856e-06,   1.215691e-04],
#>                 [  6.707491e-04,   8.258528e-04,   1.367066e-04]])
```

In [22]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3

# 答案:
np.set_printoptions(suppress=True, precision=6)  # precision 是可选项
rand_arr

array([[ 0.000543,  0.000278,  0.000425],
       [ 0.000845,  0.000005,  0.000122],
       [ 0.000671,  0.000826,  0.000137]])

### 挑战 23 ：按要求打印数组（三）
要求：打印 a 时省略中间元素，限制显示数组元素的个数为 6。
```python
# 输入数组
a = np.arange(15)
#> 原输出 ：[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]
#> 目标输出：[ 0  1  2 ..., 12 13 14]
```

In [23]:
a = np.arange(15)
# 答案:
np.set_printoptions(threshold=6)
a = np.arange(15)
print(a)

# 恢复为默认设置，因为后面的问题需要打印更多数据
np.set_printoptions(threshold=np.nan)

[ 0  1  2 ..., 12 13 14]


### 挑战 24 ：加载特殊矩阵
要求：著名的 iris 数据集是包含兰花属性和种类的数据集，其中每行属性有数字和文字，用 numpy 来加载他们。

In [24]:
# 答案
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# 输出前三行
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

### 挑战 25 ：重定义数组的元素范围
要求：将 iris 数组集的第一个列的数据范围缩放为 0 到 1。
```python
# 输入数组
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
```

In [25]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# 答案 1：
Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)
# 答案 2：
S = (sepallength - Smin)/sepallength.ptp()
print(S)

[ 0.222222  0.166667  0.111111  0.083333  0.194444  0.305556  0.083333
  0.194444  0.027778  0.166667  0.305556  0.138889  0.138889  0.        0.416667
  0.388889  0.305556  0.222222  0.388889  0.222222  0.305556  0.222222
  0.083333  0.222222  0.138889  0.194444  0.194444  0.25      0.25
  0.111111  0.138889  0.305556  0.25      0.333333  0.166667  0.194444
  0.333333  0.166667  0.027778  0.222222  0.194444  0.055556  0.027778
  0.194444  0.222222  0.138889  0.222222  0.083333  0.277778  0.194444
  0.75      0.583333  0.722222  0.333333  0.611111  0.388889  0.555556
  0.166667  0.638889  0.25      0.194444  0.444444  0.472222  0.5       0.361111
  0.666667  0.361111  0.416667  0.527778  0.361111  0.444444  0.5       0.555556
  0.5       0.583333  0.638889  0.694444  0.666667  0.472222  0.388889
  0.333333  0.333333  0.416667  0.472222  0.305556  0.472222  0.666667
  0.555556  0.361111  0.333333  0.333333  0.5       0.416667  0.194444
  0.361111  0.388889  0.388889  0.527778  0.222222 

### 挑战 26 ：根据百分比大小返回元素
要求：返回数组中按从小到大排序，位置为 5% 和 95% 的数。
```python
# 输入数组
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
```

In [26]:
# 答案:
np.percentile(sepallength, q=[5, 95])

array([ 4.6  ,  7.255])

### 挑战 27 ：找出数组的缺失值
要求：数组中有多处缺失值（nan），找出他们的位置。
```python
# 输入数组
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
```

In [27]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# 答案:
print("Number of missing values: \n", np.isnan(iris_2d[:, 0]).sum())
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:, 0])))

Number of missing values: 
 2
Position of missing values: 
 (array([67, 93]),)


### 挑战 28 ：数组缺失值判断
要求：返回数组是否具有缺失值。
```python
# 输入数组
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```

In [28]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# 答案:
np.isnan(iris_2d).any()

False

### 挑战 29 ：数组缺失值处理
要求：替换数组中的缺失值为0。

```python
# 输入数组
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
```

In [29]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# 答案
iris_2d[np.isnan(iris_2d)] = 0
iris_2d[:4]

array([[ 5.1,  3.5,  1.4,  0. ],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2]])

### 挑战 30 ：数组的 unique 元素
要求：返回数组中出现的所有元素集合
```python
# 输入数组
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
```

In [30]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# 答案:
species = np.array([row.tolist()[4] for row in iris])
np.unique(species, return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype='|S15'), array([50, 50, 50]))

### 挑战 31 ：二维数组排序
要求：根据第一列排序二维数组
```python
# 输入数组
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
```

In [31]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# 答案:
print(iris[iris[:,0].argsort()][:5])

[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.5' b'2.3' b'1.3' b'0.3' b'Iris-setosa']]


### 挑战 32 ：出现最频繁的元素
要求：返回数组中出现最多的元素。
```python
# 输入数组
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
```

In [32]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# 答案:
vals, counts = np.unique(iris[:, 2], return_counts=True)
print(vals[np.argmax(counts)])

b'1.5'


### 挑战 33 ：找出数组中某元素满足第一次大于某数的下标
要求：在 iris 数据集中，返回第一个元素的下标，满足第4列属性大于1.0。
```python
# 输入数组
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
```

In [33]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# 答案:
np.argwhere(iris[:, 3].astype(float) > 1.0)[0]

array([50])

### 挑战 34 ：设定数组元素的上下限
要求：给定数组 a，将数组中大于 30 的数截断为 30，小于 10 的数截断为 10。
```python
# 输入数组
np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50, 20)
```

In [34]:
np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50, 20)

# 答案 1: 使用 np.clip
np.clip(a, a_min=10, a_max=30)

# 答案 2: 使用 np.where
print(np.where(a < 10, 10, np.where(a > 30, 30, a)))

[ 27.63  14.64  21.8   30.    10.    10.    30.    30.    10.    29.18  30.
  11.25  10.08  10.    11.77  30.    30.    10.    30.    14.43]


### 挑战 35 ：去掉所有缺失值
要求：给定一维数组 a 包含缺失值，去掉他们。
```python
# 输入数组
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
```

In [35]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])

# 答案:
a[~np.isnan(a)]

array([ 1.,  2.,  3.,  5.,  6.,  7.])