# numpy 学习过程

## 创建 ndarray

In [2]:
import numpy as np

In [9]:
data1=[1,2,3.5,5,6]
ndata1=np.array(data1)
print(ndata1)

[1.  2.  3.5 5.  6. ]


In [13]:
ndata1.shape

(5,)

In [14]:
ndata1.dtype

dtype('float64')

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [18]:
# empty 不会初始化值，都是一些垃圾值
np.empty((2,3,2))

array([[[1.39415123e-311, 6.36598740e-314],
        [0.00000000e+000, 1.27319747e-313],
        [1.27319747e-313, 1.27319747e-313]],

       [[1.27319747e-313, 1.27319747e-313],
        [7.35369147e-043, 2.31819566e-052],
        [2.62696831e-313, 1.71663903e+185]]])

In [ ]:
np.